# # Using Keras



In [ ]:
from keras import backend as K

import keras
import keras
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD
from keras.models import Sequential

import numpy as np

In [ ]:
import numpy as np
x_train = np.random.random((1000, 20))
y_train = keras.utils.to_categorical(np.random.randint(10, size=(1000, 1)), num_classes=10)
x_test = np.random.random((100, 20))
y_test = keras.utils.to_categorical(np.random.randint(10, size=(100, 1)), num_classes=10)

model = Sequential()
# Dense(64) is a fully-connected layer with 64 hidden units.
# in the first layer, you must specify the expected input data shape:
# here, 20-dimensional vectors.
model.add(Dense(32, activation='linear', input_dim=20))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

In [ ]:
#sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
#model.compile(loss='categorical_crossentropy',
#              optimizer=sgd,
#              metrics=['accuracy'])

#model.fit(x_train, y_train,
#          epochs=20,
#          batch_size=128)
#score = model.evaluate(x_test, y_test, batch_size=128)

In [ ]:
keras.activations.linear(2)

2

In [ ]:
keras.backend.ones(1)

<tf.Variable 'Variable_3:0' shape=(1,) dtype=float32_ref>

In [ ]:
tf.constant(1)

<tf.Tensor 'Const_9:0' shape=() dtype=int32>

---

#### 참고 : https://stackoverflow.com/questions/41711190/keras-how-to-get-the-output-of-each-layer
> dropout 이용시 train/test 에서 K.learning_phase() 부분 조절해야하는거 주의해

In [ ]:
inp = model.input                                           # input placeholder
outputs = [layer.output for layer in model.layers]          # all layer outputs
functors = [K.function([inp,tf.constant(1)], [out]) for out in outputs]    # evaluation functions

# Testing
test = np.random.random(input_shape)
layer_outs = [func([test, 1.]) for func in functors]
print(layer_outs)

[[array([[ 5.1506072e-01,  9.8431486e-01, -9.0443641e-02, ...,
         3.0682158e-01, -1.0763182e-02, -4.0872371e-01],
       [ 8.1182325e-01,  1.4754518e+00, -2.5560656e-01, ...,
         5.4014778e-01,  9.4316673e-04, -2.2280490e-01],
       [ 4.6702722e-01,  1.2624915e+00,  9.0584584e-02, ...,
         5.4992419e-02, -4.7755820e-01,  2.4008067e-01],
       ...,
       [ 1.4017247e-01,  5.2658349e-01,  3.9611474e-02, ...,
        -3.3093318e-01, -5.1053083e-01,  1.6784312e-01],
       [-2.6104566e-01,  6.2130642e-01, -3.0249029e-01, ...,
         1.0786407e-01, -4.9843550e-01,  2.4109557e-01],
       [ 5.4343259e-01,  1.1704438e+00,  2.8179649e-01, ...,
         5.6032354e-01, -3.9842221e-01, -1.5912291e-01]], dtype=float32)], [array([[ 5.1506072e-01,  9.8431486e-01, -9.0443641e-02, ...,
         3.0682158e-01, -1.0763182e-02, -4.0872371e-01],
       [ 8.1182325e-01,  1.4754518e+00, -2.5560656e-01, ...,
         5.4014778e-01,  9.4316673e-04, -2.2280490e-01],
       [ 4.6702722e-01,

In [ ]:
len(layer_outs)

3

In [ ]:
layer_outs[0][0].shape

(100, 32)

In [ ]:
layer_outs[0][0][0] # activation layer

array([ 0.5150607 ,  0.98431486, -0.09044364,  0.53017706,  0.29694298,
        0.12439929,  0.44024926,  0.7645621 ,  0.25439313, -0.9118918 ,
        0.00446059, -0.882775  ,  0.34266365, -0.09092186, -0.34899232,
        0.5617124 , -0.12938619,  0.46718925,  0.12186783,  0.91483766,
        1.0020276 ,  0.29494512, -0.62911934,  0.21391585, -0.45598033,
       -0.07593847, -0.6864741 ,  0.10111892,  0.3197538 ,  0.30682158,
       -0.01076318, -0.4087237 ], dtype=float32)

In [ ]:
layer_outs[0][0][1] # activation layer

array([ 8.1182325e-01,  1.4754518e+00, -2.5560656e-01,  5.7620770e-01,
        4.6846938e-01, -5.1902384e-01,  4.1907474e-01,  5.0967342e-01,
        1.0111144e-01, -4.8208818e-01,  4.1254008e-01, -8.7165278e-01,
       -2.3340294e-01,  4.2256349e-01, -9.7556464e-02,  6.4602189e-02,
       -4.1962081e-01,  5.7417989e-01, -1.9253410e-01,  1.2699641e+00,
        1.1242369e+00, -8.9585274e-02, -5.8842266e-01, -9.2666507e-02,
       -2.9957646e-01,  1.9675429e-01, -5.2397591e-01, -8.4208190e-01,
        5.0015342e-01,  5.4014778e-01,  9.4316673e-04, -2.2280490e-01],
      dtype=float32)

In [ ]:
layer_outs[1][0][0] # dropout layer

array([ 0.5150607 ,  0.98431486, -0.09044364,  0.53017706,  0.29694298,
        0.12439929,  0.44024926,  0.7645621 ,  0.25439313, -0.9118918 ,
        0.00446059, -0.882775  ,  0.34266365, -0.09092186, -0.34899232,
        0.5617124 , -0.12938619,  0.46718925,  0.12186783,  0.91483766,
        1.0020276 ,  0.29494512, -0.62911934,  0.21391585, -0.45598033,
       -0.07593847, -0.6864741 ,  0.10111892,  0.3197538 ,  0.30682158,
       -0.01076318, -0.4087237 ], dtype=float32)

In [ ]:
layer_outs[1][0][1] # dropout layer

array([ 8.1182325e-01,  1.4754518e+00, -2.5560656e-01,  5.7620770e-01,
        4.6846938e-01, -5.1902384e-01,  4.1907474e-01,  5.0967342e-01,
        1.0111144e-01, -4.8208818e-01,  4.1254008e-01, -8.7165278e-01,
       -2.3340294e-01,  4.2256349e-01, -9.7556464e-02,  6.4602189e-02,
       -4.1962081e-01,  5.7417989e-01, -1.9253410e-01,  1.2699641e+00,
        1.1242369e+00, -8.9585274e-02, -5.8842266e-01, -9.2666507e-02,
       -2.9957646e-01,  1.9675429e-01, -5.2397591e-01, -8.4208190e-01,
        5.0015342e-01,  5.4014778e-01,  9.4316673e-04, -2.2280490e-01],
      dtype=float32)

In [ ]:
test.shape

(100, 20)

In [ ]:
test[0]

array([0.8893357 , 0.43143761, 0.02439543, 0.00859107, 0.93649716,
       0.42165377, 0.65446498, 0.61120009, 0.8373355 , 0.54314897,
       0.98396332, 0.6923589 , 0.80863003, 0.88335972, 0.32459548,
       0.98302517, 0.69327279, 0.63857993, 0.85762348, 0.53194668])

In [ ]:
layer_outs[2][0][0]

array([0.11203962, 0.07440808, 0.04942252, 0.08553314, 0.0494111 ,
       0.09261117, 0.24445887, 0.14069672, 0.06326213, 0.08815657],
      dtype=float32)

---

# # Using torch

In [ ]:
import torch

In [ ]:
seq = torch.nn.Sequential(torch.nn.Linear(5,5), torch.nn.Dropout(0.5), torch.nn.Linear(5,1))

In [ ]:
print(seq)

Sequential(
  (0): Linear(in_features=5, out_features=5, bias=True)
  (1): Dropout(p=0.5, inplace=False)
  (2): Linear(in_features=5, out_features=1, bias=True)
)


In [ ]:
seq_linear = torch.nn.Sequential(torch.nn.Linear(5,5), torch.nn.Dropout(0), torch.nn.Linear(5,1))

In [ ]:
print(seq_linear)

Sequential(
  (0): Linear(in_features=5, out_features=5, bias=True)
  (1): Dropout(p=0, inplace=False)
  (2): Linear(in_features=5, out_features=1, bias=True)
)


In [ ]:
x_input = torch.rand(5,5)

In [ ]:
x_input

tensor([[0.8616, 0.4307, 0.9623, 0.2883, 0.2503],
        [0.2414, 0.9036, 0.4116, 0.4955, 0.5876],
        [0.9047, 0.2722, 0.3522, 0.1974, 0.4571],
        [0.1694, 0.3951, 0.9033, 0.1939, 0.6779],
        [0.7319, 0.5374, 0.2825, 0.5095, 0.4292]])

In [ ]:
x = x_input

for layer in seq:
     x = layer( x )
     print(x)

tensor([[ 0.5722,  0.4116, -0.6844, -0.3881, -0.1378],
        [ 0.3188,  0.0021, -0.5591, -0.5653, -0.0103],
        [ 0.2475,  0.2704, -0.5131, -0.5304,  0.0151],
        [ 0.3134,  0.4058, -0.7244, -0.4345, -0.2431],
        [ 0.3272,  0.1133, -0.5075, -0.5661,  0.0573]],
       grad_fn=<AddmmBackward>)
tensor([[ 1.1445,  0.0000, -0.0000, -0.7761, -0.2755],
        [ 0.6376,  0.0042, -1.1181, -0.0000, -0.0206],
        [ 0.0000,  0.0000, -0.0000, -0.0000,  0.0301],
        [ 0.6269,  0.8115, -1.4488, -0.8691, -0.0000],
        [ 0.6543,  0.0000, -1.0150, -1.1323,  0.0000]], grad_fn=<MulBackward0>)
tensor([[0.7590],
        [0.6468],
        [0.4148],
        [0.2001],
        [0.4487]], grad_fn=<AddmmBackward>)


In [ ]:
x = x_input

for layer_linear in seq_linear:
     x = layer_linear(x)
     print(x)

tensor([[ 0.4457,  0.1040, -0.0311, -0.7515,  0.1933],
        [ 0.4561,  0.0877, -0.0414, -0.4198,  0.1673],
        [ 0.5982, -0.0218, -0.0540, -0.7253,  0.4110],
        [ 0.0226,  0.5127, -0.3127, -0.4941,  0.4292],
        [ 0.6984, -0.0861,  0.0573, -0.6336,  0.2274]],
       grad_fn=<AddmmBackward>)
tensor([[ 0.4457,  0.1040, -0.0311, -0.7515,  0.1933],
        [ 0.4561,  0.0877, -0.0414, -0.4198,  0.1673],
        [ 0.5982, -0.0218, -0.0540, -0.7253,  0.4110],
        [ 0.0226,  0.5127, -0.3127, -0.4941,  0.4292],
        [ 0.6984, -0.0861,  0.0573, -0.6336,  0.2274]],
       grad_fn=<AddmmBackward>)
tensor([[-0.2336],
        [-0.0811],
        [-0.3334],
        [-0.2729],
        [-0.1930]], grad_fn=<AddmmBackward>)
